import type {
  Checklist,
  ChecklistItem,
  DashboardStats,
  Execution,
  Finding,
  Location,
  Machine,
  Organization,
  Profile,
} from '@/types'

const now = new Date()
const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()

export const MOCK_ORG: Organization = {
  id: '11111111-0000-0000-0000-000000000001',
  name: 'Demo Ops',
  slug: 'demo-ops',
  plan: 'free',
  settings: {},
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const MOCK_PROFILE_IDS = {
  admin: '22222222-0000-0000-0000-000000000001',
  supervisor: '22222222-0000-0000-0000-000000000002',
  operator: '22222222-0000-0000-0000-000000000003',
} as const

export const MOCK_PROFILES: Profile[] = [
  {
    id: MOCK_PROFILE_IDS.admin,
    org_id: MOCK_ORG.id,
    full_name: 'Admin Demo',
    role: 'admin',
    department: 'Ops',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: MOCK_PROFILE_IDS.supervisor,
    org_id: MOCK_ORG.id,
    full_name: 'Supervisor Demo',
    role: 'supervisor',
    department: 'Floor',
    badge_number: 'SUP-001',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: MOCK_PROFILE_IDS.operator,
    org_id: MOCK_ORG.id,
    full_name: 'Operador Demo',
    role: 'operator',
    department: 'Line 1',
    badge_number: 'OP-001',
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const MOCK_LOCATIONS: Location[] = [
  {
    id: 'loc-001',
    org_id: MOCK_ORG.id,
    name: 'Area Demo',
    code: 'AREA-01',
    created_at: '2024-01-01T00:00:00Z',
  },
]

export const MOCK_MACHINES: Machine[] = [
  {
    id: 'mach-001',
    org_id: MOCK_ORG.id,
    location_id: 'loc-001',
    name: 'Equipo Demo A',
    code: 'EQ-A',
    type: 'machine',
    status: 'active',
    priority: 'high',
    description: 'Referencia minima para listas y detalle.',
    specs: { sample: true },
    tags: ['demo'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    _checklist_count: 1,
    _open_findings: 1,
    _last_execution: hoursAgo(4),
  },
  {
    id: 'mach-002',
    org_id: MOCK_ORG.id,
    location_id: 'loc-001',
    name: 'Equipo Demo B',
    code: 'EQ-B',
    type: 'equipment',
    status: 'maintenance',
    priority: 'medium',
    description: 'Segundo registro de referencia.',
    specs: { sample: true },
    tags: ['demo'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    _checklist_count: 1,
    _open_findings: 0,
  },
]

export const MOCK_CHECKLIST_ITEMS: Record<string, ChecklistItem[]> = {
  'cl-001': [
    {
      id: 'item-001',
      checklist_id: 'cl-001',
      position: 1,
      item_type: 'check',
      title: 'Confirmar estado general',
      description: 'Chequeo basico de arranque.',
      is_required: true,
      is_critical: true,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'item-002',
      checklist_id: 'cl-001',
      position: 2,
      item_type: 'measure',
      title: 'Registrar lectura',
      description: 'Valor de referencia.',
      is_required: true,
      is_critical: false,
      unit: 'psi',
      min_value: 10,
      max_value: 20,
      target_value: 15,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'item-003',
      checklist_id: 'cl-001',
      position: 3,
      item_type: 'text',
      title: 'Nota opcional',
      is_required: false,
      is_critical: false,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  'cl-002': [
    {
      id: 'item-101',
      checklist_id: 'cl-002',
      position: 1,
      item_type: 'check',
      title: 'Validar bloqueo',
      is_required: true,
      is_critical: true,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
}

export const MOCK_CHECKLISTS: Checklist[] = [
  {
    id: 'cl-001',
    org_id: MOCK_ORG.id,
    machine_id: 'mach-001',
    name: 'Checklist Demo Operativo',
    description: 'Plantilla corta de referencia.',
    version: 1,
    status: 'active',
    priority: 'high',
    frequency: 'daily',
    estimated_min: 10,
    required_role: 'operator',
    tags: ['demo'],
    is_template: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    _item_count: 3,
  },
  {
    id: 'cl-002',
    org_id: MOCK_ORG.id,
    machine_id: 'mach-002',
    name: 'Checklist Demo Mantenimiento',
    description: 'Segundo registro para filtros y relacion.',
    version: 1,
    status: 'draft',
    priority: 'medium',
    frequency: 'manual',
    estimated_min: 15,
    required_role: 'supervisor',
    tags: ['demo'],
    is_template: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    _item_count: 1,
  },
]

export const MOCK_EXECUTIONS: Execution[] = [
  {
    id: 'exec-001',
    org_id: MOCK_ORG.id,
    checklist_id: 'cl-001',
    machine_id: 'mach-001',
    executed_by: MOCK_PROFILE_IDS.operator,
    status: 'in_progress',
    priority: 'high',
    scheduled_at: hoursAgo(2),
    started_at: hoursAgo(1),
    metadata: {},
    created_at: hoursAgo(2),
    updated_at: hoursAgo(1),
  },
  {
    id: 'exec-002',
    org_id: MOCK_ORG.id,
    checklist_id: 'cl-002',
    machine_id: 'mach-002',
    assigned_to: MOCK_PROFILE_IDS.operator,
    status: 'failed',
    priority: 'medium',
    scheduled_at: hoursAgo(24),
    started_at: hoursAgo(23),
    completed_at: hoursAgo(22),
    score: 50,
    notes: 'Referencia de fallo demo.',
    metadata: {},
    created_at: hoursAgo(24),
    updated_at: hoursAgo(22),
  },
]

export const MOCK_FINDINGS: Finding[] = [
  {
    id: 'find-001',
    org_id: MOCK_ORG.id,
    machine_id: 'mach-001',
    execution_id: 'exec-002',
    reported_by: MOCK_PROFILE_IDS.operator,
    title: 'Hallazgo demo abierto',
    description: 'Referencia minima para la vista de hallazgos.',
    severity: 'medium',
    status: 'open',
    photos: [],
    created_at: hoursAgo(20),
    updated_at: hoursAgo(20),
  },
]

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_machines: MOCK_MACHINES.length,
  active_machines: MOCK_MACHINES.filter(machine => machine.status === 'active').length,
  machines_in_maintenance: MOCK_MACHINES.filter(machine => machine.status === 'maintenance').length,
  total_checklists: MOCK_CHECKLISTS.length,
  executions_today: MOCK_EXECUTIONS.length,
  executions_completed_today: MOCK_EXECUTIONS.filter(execution => execution.status === 'completed').length,
  executions_pending: MOCK_EXECUTIONS.filter(execution => execution.status === 'pending').length,
  open_findings: MOCK_FINDINGS.filter(finding => finding.status !== 'resolved' && finding.status !== 'closed').length,
  critical_findings: MOCK_FINDINGS.filter(finding => finding.severity === 'critical').length,
  compliance_rate: 50,
  recent_executions: MOCK_EXECUTIONS,
  machines_by_status: {
    active: MOCK_MACHINES.filter(machine => machine.status === 'active').length,
    inactive: MOCK_MACHINES.filter(machine => machine.status === 'inactive').length,
    maintenance: MOCK_MACHINES.filter(machine => machine.status === 'maintenance').length,
    decommissioned: MOCK_MACHINES.filter(machine => machine.status === 'decommissioned').length,
  },
}
